name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release
  USE_LAPACK_64: ON

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install dependecies
      run: |
        sudo apt update
        sudo apt install --no-install-recommends --no-upgrade -y just re2c libopenblas64-dev liblapacke64-dev libopenblas-dev liblapacke-dev valgrind ninja-build libjemalloc-dev

    - name: Debug
      run: |
        just test
        bin/niko -h
        build/niko -e "\i"

    - name: Release
      run: |
        just release
        bin/niko -h
        build/niko -e "\i"

    - name: Valgrind Debug
      run: just valgrind Debug

    - name: Valgrind Release
      run: just valgrind Release
