name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CMAKE_CXX_COMPILER: g++-14
jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install dependecies
      run: |
        sudo apt remove needrestart
        sudo apt update
        sudo apt install --no-install-recommends --no-upgrade -y gcc-14 just re2c valgrind ninja-build libjemalloc-dev

    - name: Debug
      run: |
        just test
        bin/niko -h
        bin/niko -e "\i"

    - name: Release
      run: |
        just release
        bin/niko -h
        bin/niko -e "\i"

    - name: Valgrind Debug
      run: just valgrind Debug

    - name: Valgrind Release
      run: just valgrind Release
