name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release
  USE_LAPACK_64: ON

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install dependecies
      run: |
        sudo apt-get install just re2c libopenblas64-dev liblapacke64-dev libopenblas-dev liblapacke-dev valgrind

    - name: Debug
      run: just test

    - name: Release
      run: just release

    - name: Verify Clean Git Tree
      run: git diff --exit-code

    - name: Valgrind
      run: just valgrind

