name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install dependecies
      run: |
        sudo apt-get install just re2c libopenblas-dev liblapacke-dev
        export CMAKE_EXE_LINKER_FLAGS="-llapacke"

    - name: Debug
      run: CMAKE_EXE_LINKER_FLAGS="-llapacke" just test

    - name: Release
      run: CMAKE_EXE_LINKER_FLAGS="-llapacke" just release

    - name: Verify Clean Git Tree
      run: git diff --exit-code
